### PR TITLE
Mysql fix

### LINKED ISSUE #885: Node-Reaccessibled crash with "Uncaught Exception" if the Database is not more accessible
Using "node-red-node-mysql 1.0.0" **if the connection to the MariaDB stops to work** we get the following error and **Node-Red crash**:

Warning: got packets out of order. Expected 7 but received 1
Warning: got packets out of order. Expected 7 but received 1
17 Feb 12:54:11 - [red] Uncaught Exception:
17 Feb 12:54:11 - TypeError: Cannot read property 'release' of undefined
at /root/.node-red/node_modules/node-red-node-mysql/68-mysql.js:117:38
at /root/.node-red/node_modules/mysql2/lib/pool.js:60:18
at PoolConnection. (/root/.node-red/node_modules/mysql2/lib/connection.js:775:13)
at Object.onceWrapper (events.js:421:26)
at PoolConnection.emit (events.js:326:22)
at PoolConnection.notifyError (/root/.node-red/node_modules/mysql2/lib/connection.js:236:12)
at Socket. (/root/.node-red/node_modules/mysql2/lib/connection.js:107:12)
at Socket.emit (events.js:314:20)
at TCP. (net.js:676:12)

**This happens only if the connection was working and suddenly stops to work**.
We get this problem on a device "Siemens IOT 2050" mounting Debian OS.

17 Feb 14:43:01 - [info] Node-RED version: v2.0.6
17 Feb 14:43:01 - [info] Node.js version: v12.22.5
17 Feb 14:43:01 - [info] Linux 5.10.64 arm64 LE
17 Feb 14:43:04 - [info] Loading palette nodes
17 Feb 14:43:19 - [info] Dashboard version 2.30.0 started at /ui
17 Feb 14:43:20 - [info] Settings file : /root/.node-red/settings.js
17 Feb 14:43:20 - [info] Context store : 'default' [module=memory]
17 Feb 14:43:20 - [info] User directory : /root/.node-red
17 Feb 14:43:20 - [warn] Projects disabled : editorTheme.projects.enabled=false
17 Feb 14:43:20 - [info] Flows file : /root/.node-red/flows.json
17 Feb 14:43:20 - [info] Server now running at http://127.0.0.1:1880/
17 Feb 14:43:20 - [warn]

I know it's not the latest Node-Red version but this device it's not so easy to upgrade.
Thanks in advance for your work and your time

### PR DESCRIPTION
**Pull request by hardillb**
- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

## Proposed changes

Add test to see if `conn` object exists before trying to release it

Fixes #885 

## Checklist

- [x] I have read the [contribution guidelines](https://github.com/node-red/node-red-nodes/blob/master/CONTRIBUTING.md)
- [x] For non-bugfix PRs, I have discussed this change on the forum/slack team.
- [x] I have run `grunt` to verify the unit tests pass
- [ ] I have added suitable unit tests to cover the new/changed functionality

### CODE REVIEW

File: storage/mysql/68-mysql.js [hunk 1]
```diff
@@ -114,7 +114,9 @@ module.exports = function(RED) {
                         //console.log("query:",msg.topic);
                         node.mydbConfig.pool.getConnection(function (err, conn) {
                             if (err) {
-                                conn.release()
+                                if (conn) {
```
Comment (dceejay) [inline storage/mysql/68-mysql.js:117]: just checking (I haven't ;-) - does releasing conn then let the auto connect reconnect correctly also ?

Comment (hardillb) [reply storage/mysql/68-mysql.js:117]: Don't know, I was just fixing the bug in the referenced issue which was definitely caused by `conn` being undefined at the point of failure.

Comment (lucagem) [reply storage/mysql/68-mysql.js:117]: Ok, well done.

**Node-Red does not crash anymore** and when MySQL come back the Node **reconnect fine**.

The only things I noticed is the Node-Red logs continuously.
node-red log

Comment (hardillb) [reply storage/mysql/68-mysql.js:117]: That's going to be driven by your incoming message rate so it's one log for every failed query. 

I'm  tempted to say that it should log a failure if it can't connect and it's up to the user to use something like a catch node to handle the failure.

**Comment by lucagem** [comment]
OK, thanks a lot
